In [33]:
import pandas as pd
df = pd.read_csv('https://github.com/lovedlim/bigdata_analyst_cert_v2/blob/main/part1/ch3/type1_data1.csv?raw=true') # 깃허브 주소에 ?raw=true 붙이기
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

필터링, 최솟값, 중앙값

In [ ]:
# f5칼럼이 0이 아닌 행을 구하시오.
c1 = df['f5'] != 0
df = df[c1]
df

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [ ]:
# views 칼럼 결측치를 views칼럼의 최솟값으로 채우시오.
min = df['views'].min()
df['views'].fillna(min, inplace = True)
df

/tmp/ipython-input-9-4075788828.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(min, inplace = True)
/tmp/ipython-input-9-4075788828.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'].fillna(min, inplace = True)

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [ ]:
# views 칼럼의 중앙값을 계산해 점수로 구하시오.
int(df['views'].median())

5924

카테고리, 인덱스, 문자열 슬라이싱

In [ ]:
# subscribed 칼럼에서 가장 빈도수가 많은 날짜를 구하시오
values = df['subscribed'].value_counts()
values

subscribed
2025-02-17    16
2024-06-21     3
2024-07-16     2
2024-04-03     2
2024-02-09     2
              ..
2024-05-06     1
2024-10-02     1
2024-12-02     1
2025-01-29     1
2025-01-30     1
Name: count, Length: 96, dtype: int64

In [ ]:
# 앞에서 구한 날짜의 일(day)값을 정수로 구하시오
int(values.index[0][-2:])

17

파생변수, 정렬, 인덱싱

In [ ]:
# 결측치가 있는 데이터(행)을 제거하기
df.dropna(inplace = True)

In [ ]:
# views칼럼을 f1칼럼으로 나눈 값을 새로운 칼럼으로 추가하기
df['views/f1'] = df['views']/df['f1']
df

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,views/f1
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,86.584615
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,105.583333
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,100.661538
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,25.063830

In [ ]:
# 새로운 칼럼 중 가장 큰 값을 가진 행의 age를 정수로 구하기
df.sort_values('views/f1',ascending = False, inplace = True)
int(df.iloc[0,1])

22

값 변경, 정렬, 합계

In [ ]:
df['views'].fillna(0, inplace = True) # views칼럼의 데이터를 0으로 대체하기
df

/tmp/ipython-input-3-1535764367.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(0, inplace = True) # views칼럼의 데이터를 0으로 대체하기

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [ ]:
# views 칼럼에서 상위 10번째 값을 구하기
df = df.sort_values('views', ascending = False)
views_10thmin = df.iloc[:10]['views'].min()
views_10thmin

9877.0

In [ ]:
# 상위 10개의 값을 상위 10번째 값으로 대체하기
df.iloc[:10,-1] = views_10thmin
df

       id   age city    f1  f2   f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..    ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93   id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
48   id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39   id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
20   id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
82   id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [ ]:
print(int(df['views'].sum())) # views 칼럼의 전체 합을 정수로 구하기

652812

In [ ]:
# 다른 방법
df['views'].fillna(0, inplace = True)
views_10thmin = df['views'].nlargest(10).iloc[-1]
df.loc[df['views']>views_10thmin, 'views'] = views_10thmin
print(int(df['views'].sum()))

652812

/tmp/ipython-input-12-2079626731.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['views'].fillna(0, inplace = True)

문자열 슬라이싱, 파생변수, 평균값

In [ ]:
# f4 칼럼 데이터에 FJ가 포하된 데이터 찾기
df['new'] = df['f4'].str[-2:]
cond = df['new'] == 'FJ'
FJ = df[cond]
FJ

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
0,id01,2.0,서울,NaN,0,gold,ENFJ,91.297791,2024-07-16,6820.0,FJ
1,id02,9.0,서울,70.0,1,NaN,ENFJ,60.339826,2024-05-12,2534.0,FJ
4,id05,24.0,서울,85.0,2,NaN,ISFJ,29.269869,2024-03-07,1338.0,FJ
6,id07,36.3,서울,60.0,1,NaN,ISFJ,9.796378,2024-01-11,61.0,FJ
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,FJ
8,id09,3.3,서울,35.0,2,NaN,ESFJ,17.252986,2024-03-21,2764.0,FJ
13,id13,15.0,서울,68.0,0,gold,ESFJ,83.685380,2024-12-30,5643.0,FJ
18,id18,41.0,서울,87.0,2,gold,ISFJ,80.138280,2024-03-03,7933.0,FJ
24,id24,80.0,부산,44.0,0,gold,INFJ,73.586397,2024-09-11,5976.0,FJ
31,id31,86.0,부산,77.0,0,gold,ESFJ,73.586397,2024-02-11,8014.0,FJ
32,id32,25.0,부산,64.0,0,vip,ISFJ,13.049921,2024-05-24,17421.0,FJ
33,id33,47.0,부산,94.0,0,silver,ENFJ,17.252986,2024-04-02,3880.0,FJ
39,id39,56.0,부산,50.0,0,NaN,INFJ,33.308999,2024-12-22,NaN,FJ
41,id41,81.0,대구,55.0,0,gold,ENFJ,37.113739,2024-10-04,8640.0,FJ
45,id45,97.0,대구,88.0,0,gold,ENFJ,13.049921,2024-06-21,8317.0,FJ
52,id52,97.0,대구,82.0,1,gold,ISFJ,90.496999,2024-05-20,8518.0,FJ
54,id54,53.0,대구,NaN,1,gold,ENFJ,69.730313,2024-06-21,5872.0,FJ
57,id57,3.0,대구,111.0,0,silver,ISFJ,29.269869,2024-01-12,4421.0,FJ
59,id59,64.0,대구,NaN,1,silver,ESFJ,20.129444,2024-06-23,4994.0,FJ
63,id63,88.0,경기,86.0,1,silver,ISFJ,73.586397,2024-12-01,4053.0,FJ
67,id67,66.0,경기,52.0,1,NaN,ISFJ,73.586397,2024-06-17,1159.0,FJ
73,id73,90.0,경기,NaN,1,NaN,ISFJ,73.586397,2024-08-12,512.0,FJ
81,id81,86.0,경기,50.0,1,NaN,ISFJ,37.113739,2024-09-14,244.0,FJ
85,id85,83.6,경기,55.0,0,gold,INFJ,80.138280,2024-09-24,6719.0,FJ
99,id99,1.0,경기,47.0,0,gold,ESFJ,97.381034,2024-12-02,6090.0,FJ
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,FJ
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,FJ
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,FJ

In [ ]:
print(round(FJ['f2'].mean(),2)) # 찾은 데이터 중에서 f2 칼럼의 평균값 구하기

0.61

In [ ]:
# 다른 풀이
cond = df['f4'].str.contains('FJ')
print(round(df[cond]['f2'].mean(),2))

0.61

필터링, 분산

In [ ]:
# f3칼럼이 gold이면서 f2 칼럼이 2인 데이터 구하기
cond1 = df['f3']=='gold'
cond2 = df['f2']==2
df = df[cond1 & cond2]
df

        id   age city    f1  f2    f3    f4         f5  subscribed   views
18    id18  41.0   서울  87.0   2  gold  ISFJ  80.138280  2024-03-03  7933.0
29    id29 -13.5   부산  47.0   2  gold  ENTP  67.886373  2024-08-28  6793.0
42    id42  65.0   대구  48.0   2  gold  ESTP  33.308999  2024-02-09  5999.0
55    id55  75.0   대구  63.0   2  gold  ENTP  13.049921  2024-02-06  6042.0
64    id64  43.0   경기  62.0   2  gold  ESFP  73.586397  2024-02-22  5995.0
68    id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
71    id71  35.0   경기  84.0   2  gold  ISFP  52.667078  2024-07-15  8087.0
101   id68  35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29  8599.0
112  id111  22.0   부산  65.0   2  gold  ENTP   0.000000  2025-02-17  7894.0
118  id117  23.0   대구  65.0   2  gold  INFP   0.000000  2025-02-17  6543.0

In [ ]:
# 위 데이터에서 f1칼럼의 분산 구하기
print(round(df['f1'].var(),2))

235.43

값 변경(연산), 필터링 절대값

In [ ]:
df['age'] = df['age'] + 1
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   3.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02  10.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  28.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  76.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  25.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  23.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  24.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  24.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  24.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  25.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [ ]:
cond1 = (df['age']>=30) & (df['age']<40)
cond2 = (df['age']>=20) & (df['age']<30)
print(round(abs(df[cond1]['views'].mean()-df[cond2]['views'].mean()),2))

263.13

시계열 데이터, 필터링, 데이터 개수

In [ ]:
df['subscribed'] = pd.to_datetime(df['subscribed'])
df['year'] = df['subscribed'].dt.year
df['month'] = df['subscribed'].dt.month
cond1 = df['year'] == 2024
cond2 = df['month'] == 2
cond3 = df['f3'] == 'gold'
len(df[cond1 & cond2 & cond3])

5

필터링, 카테고리, 최빈값

In [ ]:
df = df[df['views']<=1000]
print(df['f4'].value_counts().index[0])

ISFJ

In [ ]:
df = df[df['views']<=1000]
print(df['f4'].mode()[0])

ISFJ

그룹핑, 최댓값, 정렬

In [ ]:
df = df.dropna()
df = df.groupby('city').mean(numeric_only=True)
df

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

In [ ]:
df['f2'].sort_values().index[-1]

'서울'

슬라이싱, 사분위수, 결측치 제거

In [ ]:
df.dropna(inplace = True)
df

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [ ]:
end = int(len(df)*0.7)
df = df.iloc[:end]
df

       id   age city     f1  f2      f3    f4         f5  subscribed    views
2    id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5    id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7    id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9    id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10  id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
11   id11  40.0   서울   68.0   0    gold  ENFP  98.429899  2024-10-29   6752.0
13   id13  15.0   서울   68.0   0    gold  ESFJ  83.685380  2024-12-30   5643.0
14   id14  77.0   서울   50.0   1    gold  ENTJ  67.886373  2024-09-19   5700.0
15   id15  22.0   서울   67.0   1    gold  ENTP   9.796378  2024-05-26   7676.0
16   id16  68.0   서울   85.0   0    gold  ESFP  16.283854  2024-07-25   9472.0
18   id18  41.0   서울   87.0   2    gold  ISFJ  80.138280  2024-03-03   7933.0
22   id22  -6.3   부산   72.0   1    gold  ENFP  52.667078  2024-02-09   6147.0
23   id23  34.0   부산   75.0   1    gold  ISTP  69.730313  2024-05-21   6236.0
24   id24  80.0   부산   44.0   0    gold  INFJ  73.586397  2024-09-11   5976.0
26   id26  55.0   부산   57.0   1    gold  ENFP  83.685380  2024-05-01   5857.0
27   id27  37.0   부산   60.0   0  silver  ESTP  73.586397  2024-10-13   4255.0
28   id28  38.0   부산   34.0   1    gold  ENTP  80.138280  2024-10-31   5068.0
29   id29 -13.5   부산   47.0   2    gold  ENTP  67.886373  2024-08-28   6793.0
31   id31  86.0   부산   77.0   0    gold  ESFJ  73.586397  2024-02-11   8014.0
32   id32  25.0   부산   64.0   0     vip  ISFJ  13.049921  2024-05-24  17421.0
33   id33  47.0   부산   94.0   0  silver  ENFJ  17.252986  2024-04-02   3880.0
36   id36  68.0   부산   77.0   1    gold  INTP  13.049921  2024-07-20   9713.0
40   id40  56.0   대구   75.0   0    gold  ENFP  17.252986  2024-01-22   8481.0
41   id41  81.0   대구   55.0   0    gold  ENFJ  37.113739  2024-10-04   8640.0
42   id42  65.0   대구   48.0   2    gold  ESTP  33.308999  2024-02-09   5999.0
43   id43  23.0   대구   60.0   0  silver  ISTP  29.269869  2024-05-18   3878.0
45   id45  97.0   대구   88.0   0    gold  ENFJ  13.049921  2024-06-21   8317.0
47   id47  34.6   대구   75.0   1    gold  ESTJ  90.496999  2024-05-28   8628.0
49   id49  75.0   대구   88.0   0    gold  INTP  37.113739  2024-03-31   9737.0
52   id52  97.0   대구   82.0   1    gold  ISFJ  90.496999  2024-05-20   8518.0
53   id53  52.0   대구   50.0   0    gold  ESTP  20.129444  2024-09-09   7012.0
55   id55  75.0   대구   63.0   2    gold  ENTP  13.049921  2024-02-06   6042.0
57   id57   3.0   대구  111.0   0  silver  ISFJ  29.269869  2024-01-12   4421.0
63   id63  88.0   경기   86.0   1  silver  ISFJ  73.586397  2024-12-01   4053.0
64   id64  43.0   경기   62.0   2    gold  ESFP  73.586397  2024-02-22   5995.0
68   id68  35.0   경기   45.0   2    gold  ISFP  67.886373  2024-07-29   8599.0
70   id70  -9.0   경기   96.0   1  silver  ISTP  48.431184  2024-11-17   4442.0
71   id71  35.0   경기   84.0   2    gold  ISFP  52.667078  2024-07-15   8087.0
74   id74  45.0   경기   98.0   0    gold  ESTP  52.667078  2024-05-27   7739.0
75   id75  63.0   경기   47.0   0    gold  ESTP  20.129444  2024-06-12   6779.0
78   id78  92.0   경기   96.0   1    gold  INTJ  69.730313  2024-10-27   7565.0
80   id80  67.0   경기   60.0   0  silver  ISFP  83.685380  2024-01-14   4381.0
83   id83  73.0   경기   50.0   1     vip  ENTP  80.138280  2024-09-26  19139.0
84   id84  66.0   경기   44.0   0    gold  INTP  83.685380  2024-12-19   5650.0
85   id85  83.6   경기   55.0   0    gold  INFJ  80.138280  2024-09-24   6719.0
89   id89  34.0   경기   66.0   1    gold  ENTJ  33.308999  2024-10-14   6119.0
91   id91   6.0   경기   72.0   0    gold  INTP   9.796378  2024-08-23   8988.0
92   id92  97.0   경기   78.0   1    gold  INFP  97.381034  2024-05-08   9625.0
95   id95  77.0   경기   43.0   1    gold  INTJ  91.297791  2024-05-21   8697.0

In [ ]:
q3 = df['views'].quantile(.75)
q1 = df['views'].quantile(.25)
int(q3 - q1)

2771

결측치 처리, 최빈값, 데이터 개수

In [ ]:
print(df.isnull().sum())

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [ ]:
df = df.dropna(subset=['f1']) # f1의 결측치 제거
df

        id   age city    f1  f2      f3    f4         f5  subscribed    views
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07   1338.0
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
6     id07  36.3   서울  60.0   1     NaN  ISFJ   9.796378  2024-01-11     61.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[89 rows x 10 columns]

In [ ]:
freq = df['f3'].mode()[0]
freq

'gold'

In [ ]:
df['f3'].fillna(freq, inplace = True)
df

/tmp/ipython-input-55-3985496623.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['f3'].fillna(freq, inplace = True)
/tmp/ipython-input-55-3985496623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['f3'].fillna(freq, inplace = True)

        id   age city    f1  f2      f3    f4         f5  subscribed    views
1     id02   9.0   서울  70.0   1    gold  ENFJ  60.339826  2024-05-12   2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
4     id05  24.0   서울  85.0   2    gold  ISFJ  29.269869  2024-03-07   1338.0
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
6     id07  36.3   서울  60.0   1    gold  ISFJ   9.796378  2024-01-11     61.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[89 rows x 10 columns]

In [ ]:
len(df[df['f3']=='gold'])

63

In [ ]:
sum(df['f3']=='gold')

63

결측 데이터 찾기, 필터링, 평균값

In [ ]:
df = df[df['f1'].isnull()]
print(round(df['age'].mean(),1))

53.6

중복 데이터 제거, 값 변경, 데이터 개수

In [ ]:
df.drop_duplicates(inplace = True)
df = df.fillna(0).replace('silver',1).replace('gold',2).replace('vip',3)
print(df['f3'].sum())

167

칼럼 삭제, 행 단위 합계, 필터링

In [ ]:
cols = df.select_dtypes(exclude='object').columns
cols

Index(['age', 'f1', 'f2', 'f5', 'views'], dtype='object')

In [ ]:
df = df[cols]
df.fillna(0, inplace = True)
df = df.T
df

/tmp/ipython-input-76-201149153.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace = True)

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
age,2.000000,9.000000,27.000000,75.000000,24.000000,22.000000,36.300000,38.00000,3.300000,95.000000,...,21.0,22.0,22.0,22.0,22.0,22.0,23.0,23.0,23.0,24.0
f1,0.000000,70.000000,61.000000,0.000000,85.000000,57.000000,60.000000,101.00000,35.000000,74.000000,...,78.0,45.0,65.0,45.0,34.0,23.0,65.0,12.0,65.0,94.0
f2,0.000000,1.000000,1.000000,2.000000,2.000000,0.000000,1.000000,1.00000,2.000000,1.000000,...,1.0,2.0,2.0,2.0,2.0,0.0,0.0,1.0,2.0,1.0
f5,91.297791,60.339826,17.252986,52.667078,29.269869,20.129444,9.796378,83.68538,17.252986,98.429899,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
views,6820.000000,2534.000000,7312.000000,493.000000,1338.000000,21550.000000,61.000000,3260.00000,2764.000000,9992.000000,...,6790.0,2112.0,7894.0,9877.0,10346.0,9747.0,5628.0,1267.0,6543.0,2356.0

In [ ]:
sum(df.sum()>3000)

88

이상치, IQR

In [ ]:
q1 = df['views'].quantile(.25)
q3 = df['views'].quantile(.75)
IQR = q3 - q1

In [ ]:
line1 = q1- 1.5 * IQR
line2 = q3+ 1.5 * IQR
cond1 = df['views']<line1
cond2 = df['views']>line2
df = df[cond1 | cond2]
print(sum(df['views']))

77699.0

이상치, 소수점 있는 데이터 찾기, 표준편차

In [ ]:
views_std = df['views'].std()
views_std

4121.626455600414

In [ ]:
df = df[-(df['age'] <= 0)]
df['age'] = round(df['age'],0)
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[110 rows x 10 columns]

결측치(뒤의 값으로 대체), 그룹합

In [10]:
df = df.fillna(method = 'bfill')
df

/tmp/ipython-input-10-659356365.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'bfill')

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울  70.0   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1    gold  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울  85.0   2     vip  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     vip  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [13]:
df = df.groupby(['city','f2']).sum(numeric_only=True).reset_index()
df

   city  f2     age      f1           f5     views
0    경기   0  1192.9  1490.0  1425.236647  154066.0
1    경기   1   997.0  1016.0   935.958628   91442.0
2    경기   2   296.0   390.0   430.186433   42709.0
3    대구   0   664.0   982.0   371.184620  100421.0
4    대구   1   393.6   471.0   404.779978   49536.0
5    대구   2   185.0   321.0    79.667919   22624.0
6    부산   0   525.0   691.0   395.272907   80460.0
7    부산   1   475.7   684.0   460.657406   51624.0
8    부산   2    38.5   189.0   101.195372   17771.0
9    서울   0   241.0   480.0   484.809540   61447.0
10   서울   1   433.3   687.0   506.371383   59111.0
11   서울   2   165.3   337.0   179.328213   22405.0

In [19]:
df.sort_values('views',ascending = False).iloc[2,0]

'경기'

시계열 데이터, 월별 집계, 인덱스

In [34]:
df['subscribed'] = pd.to_datetime(df['subscribed'])
df['month'] = df['subscribed'].dt.month
df = df.groupby('month').sum(numeric_only=True)
df.sort_values('views').index[0]

np.int32(11)